dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.7.3
  - smartcontractkit/chainlink@1.9.0

compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.7.3'
      - '@chainlink=smartcontractkit/chainlink@1.9.0'

networks:
  goerli:
    price_feed_address : "0xD4a33860578De61DBAbDc8BFdb98FD742fA7028e"
  mainnet-fork:
    price_feed_address : "0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419"